services:

  app:
    build: .
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'    # Max 50% of a single CPU core
    #       memory: 2048M   # Hard limit: container will be killed if it exceeds this
    #     reservations:
    #       cpus: '2'    # Guaranteed 25% of a CPU core
    #       memory: 2048M   # Soft limit: Docker tries to keep usage here
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      CONFIG_PATH: "./configs/local.yaml"
    ports:
      - "8080:8080"
