env: "local"
token_ttl: 15m
http_server:
  address: "0.0.0.0:8080"
  server_header: "bike-tracker"
  disable_keepalive: false
  concurrency: 262144 #256*1024
  reduce_memory_usage: false
  disable_default_date: false
  idle_timeout: 10s
  read_timeout: 2s
  write_timeout: 2s
middleware:
  rate_limit_max: 1000
  rate_limit_expiration: 60s
  token_issuer: "markosoft2000"
  token_audience: "auth-service"
services:
  auth_service_addr: "host.docker.internal:50001"
  slo:
    auth:
        user_register_timeout: 2s
        user_login_timeout: 2s
        user_logout_timeout: 2s
        user_is_admin_timeout: 2s
        refresh_token_timeout: 2s
        app_add_timeout: 2s
        app_remove_timeout: 2s
redis:
  host: "redis"
  port: 6379
  operation_timeout: 2s
kafka:
  brokers: "kafka:9092"
  user_activity_group_id: "gateway-act-group"
  user_activity_topic: "auth-user-activity-v1"
  user_activity_auto_offset_reset: "latest"
  app_public_key_group_id: "gateway-app-pk-group"
  app_public_key_topic: "auth-app-key-v1"
  app_public_key_auto_offset_reset: "earliest"  