// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package kafka

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB70d1354DecodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka(in *jlexer.Lexer, out *UserActivityEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "event_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EventType = string(in.String())
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Timestamp).UnmarshalJSON(data))
				}
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "app_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB70d1354EncodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka(out *jwriter.Writer, in UserActivityEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"event_type\":"
		out.RawString(prefix[1:])
		out.String(string(in.EventType))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Raw((in.Timestamp).MarshalJSON())
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"app_id\":"
		out.RawString(prefix)
		out.String(string(in.AppID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserActivityEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB70d1354EncodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserActivityEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB70d1354EncodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserActivityEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB70d1354DecodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserActivityEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB70d1354DecodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka(l, v)
}
func easyjsonB70d1354DecodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka1(in *jlexer.Lexer, out *AppKeyEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "event_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EventType = string(in.String())
			}
		case "public_key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "app_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB70d1354EncodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka1(out *jwriter.Writer, in AppKeyEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"event_type\":"
		out.RawString(prefix[1:])
		out.String(string(in.EventType))
	}
	{
		const prefix string = ",\"public_key\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"app_id\":"
		out.RawString(prefix)
		out.String(string(in.AppID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AppKeyEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB70d1354EncodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AppKeyEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB70d1354EncodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AppKeyEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB70d1354DecodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AppKeyEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB70d1354DecodeGithubComMarkosoft2000BikeTrackerInternalPubsubKafka1(l, v)
}
